# .mypy.ini — documented at
#   https://mypy.readthedocs.io/en/stable/config_file.html
[mypy]
warn_unused_configs = True

mypy_path = backend/tests:backend/src:backend/api
explicit_package_bases = True

check_untyped_defs = True
strict_equality = True

[mypy-google.api.*]
ignore_missing_imports = True
[mypy-google.rpc.*]
ignore_missing_imports = True
[mypy-grpc.*]
ignore_missing_imports = True
[mypy-grpc_status.*]
ignore_missing_imports = True

[mypy-todo.v1.*]
ignore_errors = True
ignore_missing_imports = True
